linters-settings:
    govet:
      check-shadowing: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    golint:
      min-confidence: 0
    gocyclo:
      min-complexity: 15
    maligned:
      suggest-new: true
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: UK
    lll:
      line-length: 140
    goimports:
      local-prefixes: github.com/golangci/golangci-lint
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - wrapperFunc
        - dupImport # https://github.com/go-critic/go-critic/issues/845
    funlen:
      lines: 100
      statements: 50


issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec # security check is not impoerant in tests
        - dupl  # we usualy duplicate code in tests

run:
  skip-dirs:
    - model
    - tmp
    - bin
    - scripts

  tests: true
  build-tags:
    - integration

linters:
  disable-all: true
  fast: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - depguard
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - golint
    - goprintffuncname
    - gosimple
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nestif
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.30.x
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
