language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/schrej/godacov

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - godacov -t $CODACY_PROJECT_TOKEN -r ./coverage.txt -c $TRAVIS_COMMIT
