language: go

dist: focal

env:
  - GO111MODULE=on

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0

install:
  - go get github.com/schrej/godacov

script:
   - make ci_tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - godacov -t $CODACY_PROJECT_TOKEN -r ./coverage.txt -c $TRAVIS_COMMIT
